### ISSUE TITLE
Error in running example

### ISSUE THREAD

**Issue by Swailem95** [FRESNA/PyPSA#15]
I just installed PyPSA and I'm trying out the first [example](https://pypsa.org/doc/quick_start.html#build-a-minimal-network-for-power-flow) in the quick start. I copied everything up until the first print statement and pasted in into my IDE. 

So the code just looks like this:

```
import pypsa
import numpy as np

network = pypsa.Network

# add three buses
for i in range(3):
    network.add("Bus","My bus {}".format(i))

print(network.buses)
```

I got an error that says:

> TypeError: add() missing 1 required positional argument: 'name'

I don't understand what I could be doing wrong, I literally just copied and pasted code from the example. I'm using Python 3.5.1.

**Comment by nworbmot** [comment]
The problem is that you didn't copy the code correctly. You need the brackets "()" after "network = pypsa.Network()" so that you instantiate the object rather than just making a reference to the class.
