### ISSUE TITLE
Can PyPSA read MATPOWER case files?

### ISSUE THREAD

**Issue by rsmith54** [FRESNA/PyPSA#21]
First, thanks for this package.  

Is there a straightforward way to read MATPOWER case files? Or alternatively, do you know the easiest way to translate MATPOWER files to PyPSA? Thanks.

**Comment by coroa** [comment]
Hi,

On Wed, Sep 06 2017, Russell Smith wrote:

> Is there a straightforward way to read MATPOWER case files? Or
> alternatively, do you know the easiest way to translate MATPOWER files
> to PyPSA? Thanks.

It does read pypower case dictionaries with io.import_from_pypower_ppc,
which are matpower files in a dictionary. I usually use the following
work-around based on octave, which can probably easily be adjusted to
matlab as well.

import os
import subprocess
from tempfile import mkstemp
import scipy.io
import pypsa

octave = "octave"
def read_matpowercase(case, matpower_dir):  # noqa: E302
    fd, tmpfn = mkstemp(); os.close(fd)  # noqa: E702

    proc = subprocess.Popen([octave, "--no-gui"], stdin=subprocess.PIPE, cwd=matpower_dir)
    proc.communicate("c = {case};\nsave -6 {tmpfn} c\n"
                     .format(case=case, tmpfn=tmpfn).encode('utf-8'))
    if proc.poll() != 0:
        raise RuntimeError("octave did not return successfully".format(octave))

    s = scipy.io.loadmat(tmpfn, squeeze_me=True, struct_as_record=False)['c']
    os.remove(tmpfn)
    return {f: getattr(s, f)
            for f in {'version', 'baseMVA', 'bus',
                      'gen', 'branch', 'gencost', 'bus_name'}
            if hasattr(s, f)}

def load_case(case, matpower_dir, overwrite_zero_s_nom=1e3):
    ppc = read_matpowercase(case, matpower_dir=matpower_dir)
    network = pypsa.Network()
    network.name = "MATPOWER {}".format(case)
    pypsa.io.import_from_pypower_ppc(network, ppc,
                                     overwrite_zero_s_nom=overwrite_zero_s_nom)
    return network

Best,
Jonas


-- 
Jonas Hörsch
Frankfurt Institute for Advanced Studies
Ruth-Moufang-Str. 1
60438 Frankfurt am Main, Germany

Tel.: +49 69 798 47605
hoersch@fias.uni-frankfurt.de

**Comment by rsmith54** [comment]
Great, thanks for the help.
