### ISSUE TITLE
Verify network settings

### ISSUE THREAD

**Issue by pavelromashkin** [FRESNA/PyPSA#22]
Hi all, I am working on adapting the PyPSA for use with neural networks. Is there a function to easily update the parameters of the network's components and verify the performance/detect invalid settings?

**Comment by coroa** [comment]
Hi Pavel,

the mailing list is better suited to questions about usage than the issue tracker. Let's please carry the discussion to https://groups.google.com/forum/#!forum/pypsa.

I am not sure I understand what you want to modify. All parameters of the components are held in pandas dataframes like network.buses, network.generators, network.storage_units and so on. That means you can use all the pandas features to update parameters. For instance, a call to
```
network.generators.loc[network.generators.carrier == 'Wind', 'p_nom_extendable'] = True
```
would allow the extension of all wind turbines.

Is that what you want?

Best,
Jonas

P.S.: Please ask follow-up questions on the mailing list i'll add a cross-link later.
