### ISSUE TITLE
Impedance in calculate_B_H

### ISSUE THREAD

**Issue by rsmith54** [FRESNA/PyPSA#23]
In this line, for a DC network the attribute selected is ```r_pu```:
https://github.com/FRESNA/PyPSA/blob/master/pypsa/pf.py#L622

This function is inspired by the equivalent PYPOWER (and by extension MATPOWER) ```makeBdc``` functions.

Based on MATPOWER and PyPOWER, I think this should be ```x_pu``` for a DC network.

https://github.com/rwl/PYPOWER/blob/master/pypower/makeBdc.py#L52
http://www.pserc.cornell.edu/matpower/docs/ref/matpower5.0/makeBdc.html (L71)

Is the output of this function used as part of the LOPF ?

**Comment by nworbmot** [comment]
There are two different means of "DC" in this context, please see [AC-DC terminology](https://pypsa.org/doc/conventions.html#ac-dc-terminology). For us, to follow [Theresa May](http://www.bbc.com/news/uk-politics-36782922), AC means AC and DC means DC. Linearised load flow means linearised load flow.
