### ISSUE TITLE
PyPSA network.pf() does not work under pandas version 0.19.0

### ISSUE THREAD

**Issue by ulfmueller** [FRESNA/PyPSA#8]
It seems that the pf functionality does not work with pandas version 0.19.0. After trying out 0.18.1. it worked again...
Have you experienced such an issue?

**Comment by nworbmot** [comment]
Hi Ulf, there was a problem with pandas 0.19.0 that should be fixed in version 0.6.2, see http://pypsa.org/doc/release_notes.html#pypsa-0-6-2-4th-november-2016 . Which version of PyPSA are you using?

**Comment by ulfmueller** [comment]
Hi Tom, I understand. I am using 0.6.1. I will update then! Thanks for the explanation and sorry for bothering (could have read those release notes)...
